Repository AY2223S1-CS2103T-T17-4/tp, pull requests merged in 2022-10, with the labels that each got.

#74 Fix UI not updating when cancel/mark/unmark commands are entered
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug, priority.High, severity.Medium

#75 Update UserGuide.md
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#76 Modify `list` command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateAppointmentException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/BookCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, type.Story, priority.Medium

#84 Add mark/unmark test for AddressBookParserTest, Fix tests in mark/unmarkCommandParserTest
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: priority.High

#81 Implement EditAppointment Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/SelectAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/EditPatientCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/UniqueAppointmentList.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BookCommandTest.java
  src/test/java/seedu/address/logic/commands/CancelCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPatientCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/testutil/AppointmentUtil.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#87 Make command words case insensitive
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Low

#91 Make `find` command filter appointment list as well
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/AppointmentOfFilteredPersonsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Enhancement, priority.Medium

#94 Remove `ListCommandParser` due to redundancy
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.Low, type.Task, severity.Low

#99 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#100 Use observables to update GUI
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#98 Branch fix bugs
  README.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPatientCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.High

#112 Add improved find
  docs/UserGuide.md
  docs/images/FindThroatTagResult.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/AppointmentOfFilteredPersonsPredicate.java
  src/main/java/seedu/address/model/person/predicates/CombinedAppointmentPredicate.java
  src/main/java/seedu/address/model/person/predicates/CombinedPersonPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/AppointmentOfFilteredPersonsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/CombinedAppointmentPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/CombinedPersonPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PredicateTestUtil.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/PredicateGeneratorUtil.java
Labels: type.Enhancement, priority.Medium

#132 Modify `Tag` to accept a restricted set of inputs only
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/BookCommandParser.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/predicates/CombinedPersonPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPatientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/person/predicates/CombinedPersonPredicateTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, severity.Medium

#114 Add hide patients/appointment command and fix edit patients bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/guanzhou03.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/HideAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/HidePatientsCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/HideAppointmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/HidePatientsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/HiddenPredicateSingleton.java
  src/main/java/seedu/address/model/person/HideAppointmentPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/EditPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/HidePatientsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HideAppointmentsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HidePatientsCommandParserTest.java
Labels: type.Story, priority.High

#131 Add `AppointmentList` to handle some operations involving `Appointment`
  src/main/java/seedu/address/logic/commands/BookCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/AppointmentList.java
Labels: priority.Low, severity.Low

#140 Adjust window sizes
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, priority.Low

#145 Add ability to `list all` patients and appointments simultaneously
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/HiddenPredicateSingleton.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: type.Enhancement, priority.Low

#149 Allow duplicate name
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.Low

#146 Fix bug that prevents removing tags from appointments with `t/`
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/EditAppointmentCommandParser.java
Labels: priority.High, type.Task, severity.High

#150 Update document for sort, group and ungroup
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ArchiveAppointmentCommand.png
  docs/images/ArchiveAppointmentSequenceDiagram.png
  docs/images/ArchivePatientCommand.png
  docs/images/ArchivePatientSequenceDiagram.png
  docs/images/GroupAppointmentCommand.png
  docs/images/GroupAppointmentSequenceDiagram.png
  docs/images/GroupPatientCommand.png
  docs/images/GroupPatientSequenceDiagram.png
  docs/images/UngroupCommand.png
  docs/images/UngroupSequenceDiagram.png
  src/main/java/seedu/address/model/person/Appointment.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Documentation, priority.Medium

#153 Add ability to `find` by appointment tags using `/ta` flag
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindClassDiagram.puml
  docs/images/FindClassDiagram.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/CombinedAppointmentPredicate.java
  src/main/java/seedu/address/model/person/predicates/CombinedPersonPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/predicates/CombinedAppointmentPredicateTest.java
  src/test/java/seedu/address/testutil/PredicateGeneratorUtil.java
Labels: type.Enhancement, priority.Medium

#151 Edit FindClassDiagram and dev guide for FindCommand slightly
  docs/DeveloperGuide.md
  docs/diagrams/FindClassDiagram.puml
  docs/images/FindClassDiagram.png
Labels: type.Documentation, priority.Low

#156 Add group by mark status function
  src/main/java/seedu/address/logic/commands/GroupAppointmentCommand.java
  src/main/java/seedu/address/model/Key.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/test/java/seedu/address/logic/commands/GroupAppointmentCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/KeyTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/UniqueAppointmentListTest.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.Enhancement, priority.Low

#141 Add history feature
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/HideAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/HidePatientsCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/UnhideAppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/UnhidePatientsCommand.java
  src/main/java/seedu/address/logic/parser/HideAppointmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/HidePatientsCommandParser.java
  src/main/java/seedu/address/logic/parser/UnhideAppointmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/UnhidePatientsCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/UniqueAppointmentList.java
  src/main/java/seedu/address/model/person/predicates/HiddenPredicateSingleton.java
  src/main/java/seedu/address/model/person/predicates/HideAppointmentPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonCommandHistoryStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AppointmentListCard.fxml
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HideAppointmentsCommandParserTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Enhancement, priority.Medium

#159 Fix mark/unmark message showing wrong appointment number
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
Labels: type.Bug, priority.High

#158 Edit user guide for Mark/Unmark/Find command
  docs/UserGuide.md
Labels: type.Documentation

#180 Add more sample data when starting a fresh instance and update MainApp Version number
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement

#181 Fix `find` command revealing hidden search results
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/predicates/CombinedAppointmentPredicate.java
  src/main/java/seedu/address/model/person/predicates/CombinedPersonPredicate.java
  src/main/java/seedu/address/model/person/predicates/HiddenPredicateSingleton.java
Labels: type.Bug, priority.Medium

#184 Fix bugs regarding edit, find, and hide composed together
  src/main/java/seedu/address/logic/commands/EditPatientCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HidePatientsCommand.java
  src/main/java/seedu/address/logic/commands/UnhideAppointmentsCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/predicates/HiddenPredicateSingleton.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HidePatientsCommandTest.java
Labels: type.Bug

#189 Fix find/hide bug
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/UnhidePatientsCommand.java
  src/main/java/seedu/address/model/AppointmentList.java
  src/main/java/seedu/address/model/person/predicates/CombinedAppointmentPredicate.java
  src/main/java/seedu/address/model/person/predicates/CombinedPersonPredicate.java
Labels: type.Bug

#230 Update UserGuide.md
  docs/UserGuide.md
  docs/images/afterHide.png
  docs/images/beforeHide.png
Labels: Bug.Documentation

#228 Improve Nicholas PPP
  docs/team/nicholastyd.md
Labels: type.Documentation

#231 Update UserGuide.md bugs
  docs/UserGuide.md
Labels: Bug.Documentation

#234 Update command formats in UG
  docs/UserGuide.md
Labels: Bug.Documentation

#235 Add UI information
  docs/UserGuide.md
  docs/images/AppointmentCard.png
  docs/images/PatientCard.png
  docs/images/SampleUI.png
Labels: type.Documentation
